### PR TITLE
ID22193: added API endpoint and user key

### PR DESCRIPTION
**Pull request by sviridovartem**

### CODE REVIEW

**Review by adolgarev — COMMENTED** [review]
Please do in one json file

**Comment by sviridovartem** [comment]
> Please do in one json file

done

**Review by adolgarev — COMMENTED** [review]
Please rename user_key_and_api_endpoint to geoap_creds

**Comment by sviridovartem** [comment]
> Please rename user_key_and_api_endpoint to geoap_creds

renamed

**Review by adolgarev — APPROVED** [review]

**Pull request merged**
